### ISSUE TITLE
How to capture website in full height

### ISSUE THREAD

**Issue by lukasoppermann** [juliangruber/url-to-screenshot#3]
Hey @juliangruber,
this project seems very nice. However I would like to capture a website in different width (to simulate devices) but always capture the entire height (which I don't know).

Is this possible? Thanks

**Comment by juliangruber** [comment]
Hey Lukas!

Yes that's possible, if you don't call `.clip()` the image will be as high as the website. `.height()` will in that case only inform the size of the virtual screen.

Hope that works!

**Comment by lukasoppermann** [comment]
Perfect, maybe you can clarify this in the readme? Thanks for the quick answer.
